### ISSUE TITLE
Provide as Docker image

### ISSUE THREAD

**Issue by brennerm** [sean0x42/markdown-extract#2]
Hey @sean0x42, thanks for the tool. :+1: Would like to integrate it into our CI pipeline but don't wanna setup a whole Rust/cargo installation. Are you willing to publish markdown-extract as a Docker image? I'm happy to help if you need any support.

**Comment by sean0x42** [comment]
I'm more than willing to look into this. Have been trying to learn more about docker recently, so I'll do some research!

**Comment by sean0x42** [comment]
@brennerm please let me know if you run into any more issues, and we can reopen this issue. Best of luck 👍
