### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by psibre** [sean0x42/markdown-extract#23]
I'm not a Rust developer, but it seems to me that the `Cargo.lock` file is missing; it's [explicitly ignored](https://github.com/sean0x42/markdown-extract/blob/c693bde0b70a7056f5d698fc961e92c101bec53f/.gitignore#L53-L55), contradicting the guidance in the comment:
```
# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock
```

Moreover, the `Cargo.lock` file is [required in the `Dockerfile`](https://github.com/sean0x42/markdown-extract/blob/c693bde0b70a7056f5d698fc961e92c101bec53f/Dockerfile#L18), so the fact that it's missing from this repo causes the build to fail.

**Comment by sean0x42** [comment]
Thanks for raising this issue @psibre. Will look into it!
